name: Build

on:
  push:
    branches: [ main ]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          vcpkg install sdl2:x64-windows
          vcpkg install imgui[opengl2-binding,sdl2-binding]:x64-windows

      - name: Configure
        run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows

      - name: Build
        run: cmake --build build --config Release

      - name: Upload exe
        uses: actions/upload-artifact@v4
        with:
          name: CoConut-Windows
          path: build/Release/CoConutEditor.exe
